version: '1'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306

  gigantic-management:
    build:
      context: .
      dockerfile: ./Backend/Gigantic-Web-Parent/Gigantic-Management/Dockerfile-dev
    container_name: gigantic-management-container
    restart: always
    depends_on:
      - mysql-db
    environment:
      - DB_HOST = mysql-db
      - DB_PORT = ${DB_PORT}
    ports: