# Docker Multi-stage build

# This Dockerfile will build a production image of the Gigantic Management Service

# Use an official Python runtime as a parent image
FROM maven:3-jdk-11
# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container